version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  addtition:
    build: ./addition
    hostname: addition
    ports:
      - 7001
    networks:
      sample:
        aliases:
          - addition
  subtraction:
    build: ./subtraction
    hostname: subtraction
    ports:
      - 5052
    networks:
      sample:
        aliases:
          - subtraction
  multiplication:
    build: ./multiplication
    hostname: multiplication
    ports:
      - 5053
    networks:
      sample:
        aliases:
          - multiplication
  division:
    build: ./division
    hostname: division
    ports:
      - 5054
    networks:
      sample:
        aliases:
          - division
  gcd:
    build: ./gcd
    hostname: gcd
    ports:
      - 5056
    networks:
      sample:
        aliases:
          - gcd
  lcm:
    build: ./lcm
    hostname: lcm
    ports:
      - 6009
    networks:
      sample:
        aliases:
          - lcm
  eq:
    build: ./eq
    hostname: eq
    ports:
      - 7001
    networks:
      sample:
        aliases:
          - eq
networks:
  sample:
